site_name: Portfólio Técnico - Charles Paiva
site_url: https://charlespaivadeveloper.github.io/portfolio-tecnico/
use_directory_urls: true
docs_dir: docs
theme:
  name: material
nav:
  - Home: index.md
  - Projetos:
      - Projeto 1: projetos/projeto1.md
      - Projeto 2: projetos/projeto2.md
  - System Design Problems:
      - Design a scheduled digital transaction system: system-design-problems/design-a-scheduled-digital-transaction-system.md


markdown_extensions:      
  - meta
  - pymdownx.details
  - pymdownx.superfences  
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - codehilite
  - toc:
      permalink: true
  - md_in_html

plugins:
  - search
  - mermaid2
