site_name: Portfólio Técnico - Charles Paiva
site_url: https://charlespaivadeveloper.github.io/portfolio-tecnico/
use_directory_urls: true
docs_dir: docs
theme:
  name: material
nav:
  - Home: index.md
  - Projetos:
      - Projeto 1: projetos/projeto1.md
      - Projeto 2: projetos/projeto2.md
  - System Design Problems:
      - Design a scheduled digital transaction system: system-design-problems/design-a-scheduled-digital-transaction-system.md
